# Generated by Django 5.1.1 on 2024-09-17 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ,.-]+$', 'Address must contain only letters, numbers, spaces, and the characters , . -')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Designation must contain only letters and spaces')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Name must contain only letters and spaces')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[\\d\\s\\-\\+]+$', 'Phone number must contain only digits, spaces, dashes, or a plus sign'), django.core.validators.RegexValidator('^.{7,15}$', 'Phone number must be between 7 and 15 characters')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Salary must be a positive number')]),
        ),
    ]
